/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuscarRemisionesNoFacturadas.java
 *
 * Created on 6/08/2012, 08:15:39 AM
 */
package corgranos.Presentacion;

import corgranos.Dominio.Core.Remision.Remision;
import corgranos.Dominio.Core.Remision.RemisionService;
import corgranos.Presentacion.ModelosDeTabla.RemisionModel;
import corgranos.Presentacion.Suscripciones.ISuscripcionBuscarRemision;
import javax.swing.JOptionPane;
import sic.Dominio.Core.Usuario.Usuario;
import sic.Dominio.Core.Usuario.UsuarioService;

/**
 *
 * @author FANNY BURGOS
 */
public class BuscarRemisionesNoFacturadas extends javax.swing.JFrame {
    private Usuario usuario;
    RemisionService rs;
    RemisionModel modelo;
    Remision remision;
    int filaseleccionada=-1;
    private ISuscripcionBuscarRemision suscripcion;
    /** Creates new form BuscarRemisionesNoFacturadas */
    public BuscarRemisionesNoFacturadas() {
        initComponents();
        rs=new RemisionService();
        UsuarioService us=new UsuarioService();
        this.setUsuario(us.getDao().ObtenerUsuario("10"));        
        this.Cargar();
    }
    public void Cargar(){
        if(this.usuario!=null){
           modelo=new RemisionModel();           
           modelo.setLista(rs.getDao().ObtenerRemisionesNoLegalizadasEnFactura(usuario.getId()));
           this.jTable1.setModel(modelo);
           this.jTable1.repaint();           
           this.jTable1.requestFocus();
           if(this.jTable1.getModel().getRowCount()>0){
              this.jTable1.changeSelection(0,0,false,false);         
           }
        }else{
            JOptionPane.showMessageDialog(this,"Debes Asignar Un Usuario ");
        }
    }
    public void Seleccionar(){
        if(this.filaseleccionada!=-1){
            this.remision=this.modelo.getRow(this.filaseleccionada);
            if(this.suscripcion!=null){
               this.suscripcion.EventoDeSeleccionRemesion();
            }
        }else{
            JOptionPane.showMessageDialog(this,"Debes Escoger una Fila");
        }
    }
    public Remision ObtenerRemisionSeleccionada(){
        return this.remision;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setEditable(false);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Remisiones No Facturadas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.filaseleccionada=this.jTable1.getSelectedRow();
        this.Seleccionar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
            this.filaseleccionada=this.jTable1.getSelectedRow();
            this.Seleccionar();    
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        this.filaseleccionada=this.jTable1.getSelectedRow();
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         if(this.suscripcion!=null){
            suscripcion.show();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BuscarRemisionesNoFacturadas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(Usuario usuario) {
        if(usuario!=null){
           this.usuario = usuario;
           this.jTextField1.setText(""+usuario.getDescripcion());
        }else{
           this.usuario=usuario;
           this.jTextField1.setText("");
        }
    }

    /**
     * @param suscripcion the suscripcion to set
     */
    public void setSuscripcion(ISuscripcionBuscarRemision suscripcion) {
        this.suscripcion = suscripcion;
    }
}
